"""Train LR on Stage A schema (Kent's 10 features incl. material_class).

Uses the multi_scenario_dataset.csv that was generated by sandbox_kent's
dataset_generator.py with Kent's feature_pipeline (so the columns include
material_class, NO wind_weighted_score).

Output: models/fire_lr_stage_c.joblib — drop-in for the orchestrator after
setting `ml_model.model_path` in default_experiment.yaml.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    f1_score,
    jaccard_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

SEED = 42
CSV_PATH = Path(__file__).resolve().parent / "dataFiles" / "multi_scenario_dataset.csv"
OUTPUT_DIR = Path(__file__).resolve().parent / "models"


def main():
    df = pd.read_csv(CSV_PATH)
    print(f"[Dataset] Loaded {len(df):,} rows")
    print(f"[Features] {list(df.columns)}")

    if "neighbor_burning_count" in df.columns:
        df = df[df["neighbor_burning_count"] > 0].copy()
        print(f"[Dataset] Filtered to susceptible cells. Rows: {len(df):,}")

    y = df["Ignited"].astype(np.int8)
    X = df.drop(columns=["Ignited"])
    feature_names = list(X.columns)
    print(f"[Features] Training on {len(feature_names)} features: {feature_names}")
    print(f"[Class balance] Positives: {int(y.sum())} / {len(y)} ({y.mean()*100:.2f}%)")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=SEED
    )

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("lr", LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="lbfgs",
            class_weight="balanced",
            max_iter=2000,
            random_state=SEED,
        )),
    ])
    pipeline.fit(X_train, y_train)

    y_proba = pipeline.predict_proba(X_test)[:, 1]
    best_f1 = 0.0
    best_threshold = 0.5
    for t in np.arange(0.1, 0.9, 0.05):
        preds = (y_proba >= t).astype(int)
        f = f1_score(y_test, preds, zero_division=0)
        if f > best_f1:
            best_f1 = f
            best_threshold = t

    y_pred = (y_proba >= best_threshold).astype(int)
    cm = confusion_matrix(y_test, y_pred)
    print()
    print("=" * 60)
    print("  STAGE C LR — PER-CELL EVALUATION (Unified 11-feature schema)")
    print("=" * 60)
    print(f"  Threshold:  {best_threshold:.2f}")
    print(f"  Confusion Matrix:")
    print(f"    {cm}")
    print(f"  Precision:  {precision_score(y_test, y_pred, zero_division=0):.4f}")
    print(f"  Recall:     {recall_score(y_test, y_pred, zero_division=0):.4f}")
    print(f"  F1:         {f1_score(y_test, y_pred, zero_division=0):.4f}")
    print(f"  AUC-ROC:    {roc_auc_score(y_test, y_proba):.4f}")
    print(f"  Jaccard:    {jaccard_score(y_test, y_pred, zero_division=0):.4f}")

    coefs = pipeline.named_steps["lr"].coef_[0]
    print()
    print("  Coefficients (signed):")
    for name, c in sorted(zip(feature_names, coefs), key=lambda p: abs(p[1]), reverse=True):
        print(f"    {name:<30}{c:>+10.4f}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / "fire_lr_stage_c.joblib"
    joblib.dump(pipeline, out_path)
    print(f"\nSaved Stage C LR: {out_path}")


if __name__ == "__main__":
    main()
